name: Check for npm dependency updates
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-npm-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update npm dependencies
        run: "npm run update-deps"

      - name: Determine whether updates were performed
        run: |
          if [ "$(git status -vv | grep -c "nothing to commit")" -ge 1 ]
          then
          echo "Nothing to update"
          exit 0
          fi

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date + '%Y-%m_%d')"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update npm dependecies"
          branch-suffix: random
          signoff: true
          delete-branch: true
          title: "chore: update npm dependencies"
          body: "Updated npm dependencies as of ${{ steps.date.outputs.date }}"
