name: Check for npm updates

on:
  schedule:
    - cron: "0 13 * * 6"

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GH_PAT}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: install npm dependencies
        run: npm ci
      - name: Check for updates
        run: npx npm-check-updates -u > updates.txt && git diff package.json | grep '^[+-]'
      - name: Create an issue if there are updates
        run: |
          if [ $? -eq 0 ]; then
            updates=$(sed '1,2d;$d' updates.txt)
            echo -e "### Description\n\nThe following npm packages should be updated to their latest versions.\n\n$updates\n\n" > issue-body.txt

            gh issue create -t "Update npm dependencies" -b "$(cat issue-body.txt)" -a ${{ secrets.GH_PAT }}
          fi
